name: Build

on:
  push:
    branches:
      - main
    paths:
      - "**.kt"
  workflow_dispatch:

jobs:
  build:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "17"

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Build
        run: |
          chmod +x gradlew
          ./gradlew :cronet:assembleRelease
